name: CMake builds for Mac and Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:
    inputs:
      release:
        required: true
        type: boolean
  workflow_dispatch:

jobs:
  build:
    name: ${{matrix.os}}, ${{matrix.compiler}}, ${{matrix.build_type}}, C++${{matrix.cpp_std}}
    runs-on: ${{matrix.os}}
    env:
      AMALGAMATING_PASSED: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        compiler: [ gcc, clang ]
        build_type: [ Release, Debug ]
        cpp_std: [ "17", "20" ]

    steps:
      - name: Initial checkout
        uses: actions/checkout@v3

      - name: "[Release] Download single header Goose"
        if: inputs.release
        uses: actions/download-artifact@v3
        with:
          name: goose-all

      - name: "[Release] Replace Goose with amalgamated single header"
        if: inputs.release
        run: mv -f goose.hpp ./include/gos/goose.hpp

      - name: Configure compiler
        run: ./ci/config_compiler.sh ${{matrix.compiler}}

      - name: Configure CMake
        run: >
          cmake -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
          -DCMAKE_C_COMPILER=${{env.CC}}
          -DCMAKE_CXX_COMPILER=${{env.CXX}}
          -DGOS_BUILD_TESTS=ON
          -DGOS_CXX_STANDARD=${{matrix.cpp_std}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} -- -j 4

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ./test/test-goose
