name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [gcc, clang]
        build_type: [Release, Debug]
        cpp_standard: ["17", "20"]

    steps:
    - uses: actions/checkout@v2

    - name: Configure compiler
      run: ./ci/config_compiler.sh ${{matrix.compiler}}

    - name: Configure CMake
      run: >
        cmake -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        -DCMAKE_C_COMPILER=${{env.CC}}
        -DCMAKE_CXX_COMPILER=${{env.CXX}}
        -DGOS_BUILD_TESTS=ON
        -DGOS_CXX_STANDARD=${{matrix.cpp_standard}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} -- -j 4

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./test/test-gos
