name: Release Goose

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  amalgamate:
    name: Amalgamate Goose into single header
    runs-on: ubuntu-latest
    steps:
      - name: Initial checkout
        uses: actions/checkout@v3

      - name: Install Quom to generate single header
        run: pip install --user quom

      - name: Amalgamate Goose into single header
        run: ~/.local/bin/quom ./include/gos/goose.hpp goose.hpp -I ./include -g SZO_GOS_.+_HPP

      - name: Upload single header Goose as artifact
        uses: actions/upload-artifact@v3
        with:
          name: goose-all
          path: goose.hpp

  build:
    uses: ./.github/workflows/cmake-builds-mac-linux.yml
    with:
      release: true

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Initial checkout
        uses: actions/checkout@v3

      - name: Download single header Goose
        uses: actions/download-artifact@v3
        with:
          name: goose-all

      - name: Release Goose
        uses: softprops/action-gh-release@v1
        with:
          files: |
            goose.hpp
            LICENSE
            README.md
