name: 'Release Goose'

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  call-amalgamate:
    uses: ./.github/workflows/amalgamate.yml

  call-cmake-builds-mac-linux:
    needs: call-amalgamate
    uses: ./.github/workflows/cmake-builds-mac-linux.yml
    with:
      release: true

  call-upload-artifact:
    needs: call-cmake-builds-mac-linux
    uses: ./.github/workflows/publish.yml
