name: Release Goose

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  amalgamate:
    name: Amalgamate Goose into single header
    runs-on: ubuntu-latest
    steps:
      - name: Initial checkout
        uses: actions/checkout@v3

      - name: Install Quom to generate single header
        run: pip install --user quom

      - name: Amalgamate Goose into single header
        run: ~/.local/bin/quom ./include/gos/goose.hpp goose.hpp -I ./include -g SZO_GOS_.+_HPP

      - name: Upload single header Goose as artifact
        uses: actions/upload-artifact@v3
        with:
          name: goose-all
          path: goose.hpp

  build:
    name: ${{matrix.os}}, ${{matrix.compiler}}, C++${{matrix.cpp_std}}
    runs-on: ${{matrix.os}}
    needs: amalgamate
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        compiler: [ gcc, clang ]
        cpp_std: [ "17", "20" ]
    steps:
      - name: Initial checkout
        uses: actions/checkout@v3

      - name: Download single header Goose
        uses: actions/download-artifact@v3
        with:
          name: goose-all

      - name: Replace Goose with amalgamated single header
        run: mv -f goose.hpp ./include/gos/goose.hpp

      - name: Configure compiler
        run: ./ci/config_compiler.sh ${{matrix.compiler}}

      - name: Configure CMake
        run: >
          cmake -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_C_COMPILER=${{env.CC}}
          -DCMAKE_CXX_COMPILER=${{env.CXX}}
          -DGOS_BUILD_TESTS=ON
          -DGOS_CXX_STANDARD=${{matrix.cpp_std}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build -- -j 4

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ./test/test-goose

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Initial checkout
        uses: actions/checkout@v3

      - name: Download single header Goose
        uses: actions/download-artifact@v3
        with:
          name: goose-all

      - name: Release Goose
        uses: softprops/action-gh-release@v1
        with:
          files: |
            goose.hpp
            LICENSE
            README.md
