name: Release Goose

permissions:
  contents: write

on:
  workflow_call:

jobs:
  debug_info:
    name: Debug Info
    runs-on: ubuntu-latest
    steps:
      - name: Print Github context
        run: echo '${{ toJSON(github) }}'

  release:
    name: Release Goose
    runs-on: ubuntu-latest
    needs: debug_info
    steps:
      - name: Initial checkout
        uses: actions/checkout@v3

      - name: Download single header Goose
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: amalgamate.yml
          name: goose-all

      - name: Release Goose
        uses: softprops/action-gh-release@v1
        with:
          files: |
            goose.hpp
            LICENSE
            README.md
