name: Release Goose

permissions:
  contents: write

on:
  workflow_run:
    workflows: [ CMake builds for Mac and Linux ]
    types: [ completed ]
  workflow_dispatch:

jobs:
  debug_info:
    name: Debug Info
    runs-on: ubuntu-latest
    steps:
      - name: Print Github context
        run: echo '${{ toJSON(github) }}'

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Release Goose
    runs-on: ubuntu-latest
    needs: debug_info
    steps:
      - name: Initial checkout
        uses: actions/checkout@v3

      - name: "[Release] Check status of building and testing"
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Building and testing workflow failed during release')

      - name: Download single header Goose
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: amalgamate.yml
          name: goose-all

      - name: Release Goose
        uses: softprops/action-gh-release@v1
        with:
          files: |
            goose.hpp
            LICENSE
            README.md
